In [95]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
pd.options.display.max_columns=None
pd.options.display.max_rows=None

In [96]:
df = pd.read_csv('archivo_unificado.csv')
df.drop('Unnamed: 0', axis = 1, inplace = True)
df.head(1)

,time,age,gender,Q3,Q4,Q5,Q6,Q8,Q11,Q13,Q15,Q20,Q21,Q22,Q23,Q25,Q26,Q33,Q35,Q41,Q7,Q9,Q12,Q14,Q16,Q17,Q24,Q32,Q34,Q10_Part_1,Q10_Part_2,Q10_Part_3,Q10_Part_4,Q10_Part_5,Q10_Part_6,Q10_Part_7,Q10_Part_8,Q10_Part_9,Q10_Part_10,Q10_Part_11,Q10_Part_12,Q10_Part_13,Q10_Part_14,Q10_Part_15,Q10_Part_16,Q10_OTHER,Q18_Part_1,Q18_Part_2,Q18_Part_3,Q18_Part_4,Q18_Part_5,Q18_Part_6,Q18_OTHER,Q19_Part_1,Q19_Part_2,Q19_Part_3,Q19_Part_4,Q19_Part_5,Q19_OTHER,Q27_A_Part_1,Q27_A_Part_2,Q27_A_Part_3,Q27_A_Part_4,Q27_A_Part_5,Q27_A_Part_6,Q27_A_Part_7,Q27_A_Part_8,Q27_A_Part_9,Q27_A_Part_10,Q27_A_Part_11,Q27_A_OTHER,Q28,Q29_A_Part_1,Q29_A_Part_2,Q29_A_Part_3,Q29_A_Part_4,Q29_A_OTHER,Q30_A_Part_1,Q30_A_Part_2,Q30_A_Part_3,Q30_A_Part_4,Q30_A_Part_5,Q30_A_Part_6,Q30_A_Part_7,Q30_A_OTHER,Q31_A_Part_1,Q31_A_Part_2,Q31_A_Part_3,Q31_A_Part_4,Q31_A_Part_5,Q31_A_Part_6,Q31_A_Part_7,Q31_A_Part_8,Q31_A_Part_9,Q31_A_OTHER,Q36_A_Part_1,Q36_A_Part_2,Q36_A_Part_3,Q36_A_Part_4,Q36_A_Part_5,Q36_A_Part_6,Q36_A_Part_7,Q36_A_OTHER,Q37_A_Part_1,Q37_A_Part_2,Q37_A_Part_3,Q37_A_Part_4,Q37_A_Part_5,Q37_A_Part_6,Q37_A_Part_7,Q37_A_OTHER,Q38_A_Part_1,Q38_A_Part_2,Q38_A_Part_3,Q38_A_Part_4,Q38_A_Part_5,Q38_A_Part_6,Q38_A_Part_7,Q38_A_Part_8,Q38_A_Part_9,Q38_A_Part_10,Q38_A_Part_11,Q38_A_OTHER,Q39_Part_1,Q39_Part_2,Q39_Part_3,Q39_Part_4,Q39_Part_5,Q39_Part_6,Q39_Part_7,Q39_Part_8,Q39_Part_9,Q39_OTHER,Q40_Part_1,Q40_Part_2,Q40_Part_3,Q40_Part_4,Q40_Part_5,Q40_Part_6,Q40_Part_7,Q40_Part_8,Q40_Part_9,Q40_Part_10,Q40_Part_11,Q40_OTHER,Q42_Part_1,Q42_Part_2,Q42_Part_3,Q42_Part_4,Q42_Part_5,Q42_Part_6,Q42_Part_7,Q42_Part_8,Q42_Part_9,Q42_Part_10,Q42_Part_11,Q42_OTHER,Q27_B_Part_1,Q27_B_Part_2,Q27_B_Part_3,Q27_B_Part_4,Q27_B_Part_5,Q27_B_Part_6,Q27_B_Part_7,Q27_B_Part_8,Q27_B_Part_9,Q27_B_Part_10,Q27_B_Part_11,Q27_B_OTHER,Q29_B_Part_1,Q29_B_Part_2,Q29_B_Part_3,Q29_B_Part_4,Q29_B_OTHER,Q30_B_Part_1,Q30_B_Part_2,Q30_B_Part_3,Q30_B_Part_4,Q30_B_Part_5,Q30_B_Part_6,Q30_B_Part_7,Q30_B_OTHER,Q31_B_Part_1,Q31_B_Part_2,Q31_B_Part_3,Q31_B_Part_4,Q31_B_Part_5,Q31_B_Part_6,Q31_B_Part_7,Q31_B_Part_8,Q31_B_Part_9,Q31_B_OTHER,Q32_B_Part_1,Q32_B_Part_2,Q32_B_Part_3,Q32_B_Part_4,Q32_B_Part_5,Q32_B_Part_6,Q32_B_Part_7,Q32_B_Part_8,Q32_B_Part_9,Q32_B_Part_10,Q32_B_Part_11,Q32_B_Part_12,Q32_B_Part_13,Q32_B_Part_14,Q32_B_Part_15,Q32_B_Part_16,Q32_B_Part_17,Q32_B_Part_18,Q32_B_Part_19,Q32_B_Part_20,Q32_B_OTHER,Q34_B_Part_1,Q34_B_Part_2,Q34_B_Part_3,Q34_B_Part_4,Q34_B_Part_5,Q34_B_Part_6,Q34_B_Part_7,Q34_B_Part_8,Q34_B_Part_9,Q34_B_Part_10,Q34_B_Part_11,Q34_B_Part_12,Q34_B_Part_13,Q34_B_Part_14,Q34_B_Part_15,Q34_B_Part_16,Q34_B_OTHER,Q36_B_Part_1,Q36_B_Part_2,Q36_B_Part_3,Q36_B_Part_4,Q36_B_Part_5,Q36_B_Part_6,Q36_B_Part_7,Q36_B_OTHER,Q37_B_Part_1,Q37_B_Part_2,Q37_B_Part_3,Q37_B_Part_4,Q37_B_Part_5,Q37_B_Part_6,Q37_B_Part_7,Q37_B_OTHER,Q38_B_Part_1,Q38_B_Part_2,Q38_B_Part_3,Q38_B_Part_4,Q38_B_Part_5,Q38_B_Part_6,Q38_B_Part_7,Q38_B_Part_8,Q38_B_Part_9,Q38_B_Part_10,Q38_B_Part_11,Q38_B_OTHER
0,910,50-54,Man,India,Bachelor’s degree,Other,5-10 years,Python,A laptop,2-5 times,5-10 years,Manufacturing/Fabrication,50-249 employees,3-4,No (we do not use ML methods),"25,000-29,999",$100-$999,NaN,NaN,"Local development environments (RStudio, Jupyt...","Python, R",Vim / Emacs,Google Cloud TPUs,"Matplotlib ,Seaborn ,Ggplot / ggplot2 ,Shiny ...","Scikit-learn , TensorFlow ,Caret","Linear or Logistic Regression, Decision Trees ...",None of these activities are an important par...,PostgreSQL,None,NaN,Colab Notebooks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"General purpose image/video tools (PIL, cv2, s...",NaN,NaN,NaN,NaN,NaN,NaN,"Word embeddings/vectors (GLoVe, fastText, word...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Platform (GCP),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Compute Engine,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Storage (GCS),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,GitHub,NaN,Kaggle,NaN,NaN,NaN,NaN,Coursera,edX,Kaggle Learn Courses,DataCamp,NaN,Udacity,Udemy,NaN,NaN,NaN,NaN,NaN,NaN,"Email newsletters (Data Elixir, O'Reilly Data ...",NaN,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...","Podcasts (Chai Time Data Science, O’Reilly Dat...","Blogs (Towards Data Science, Analytics Vidhya,...","Journal Publications (peer-reviewed journals, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
df.shape

(25973, 258)

In [98]:
def union_q10 (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12,
            columna13,columna14,columna15,columna16,columna17):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12,
             columna13,columna14,columna15,columna16,columna17]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [99]:
df['Q10'] = df.apply(lambda dataframe: union_q10(dataframe['Q10_Part_1'],dataframe['Q10_Part_2'],dataframe['Q10_Part_3'],dataframe['Q10_Part_4'],
                                          dataframe['Q10_Part_5'],dataframe['Q10_Part_6'],dataframe['Q10_Part_7'],dataframe['Q10_Part_8'],
                                          dataframe['Q10_Part_9'],dataframe['Q10_Part_10'],dataframe['Q10_Part_11'],dataframe['Q10_Part_12'],
                                          dataframe['Q10_Part_13'],dataframe['Q10_Part_14'],dataframe['Q10_Part_15'],dataframe['Q10_Part_16'],
                                          dataframe['Q10_OTHER']), axis = 1)

In [100]:
df.sample(1)

,time,age,gender,Q3,Q4,Q5,Q6,Q8,Q11,Q13,Q15,Q20,Q21,Q22,Q23,Q25,Q26,Q33,Q35,Q41,Q7,Q9,Q12,Q14,Q16,Q17,Q24,Q32,Q34,Q10_Part_1,Q10_Part_2,Q10_Part_3,Q10_Part_4,Q10_Part_5,Q10_Part_6,Q10_Part_7,Q10_Part_8,Q10_Part_9,Q10_Part_10,Q10_Part_11,Q10_Part_12,Q10_Part_13,Q10_Part_14,Q10_Part_15,Q10_Part_16,Q10_OTHER,Q18_Part_1,Q18_Part_2,Q18_Part_3,Q18_Part_4,Q18_Part_5,Q18_Part_6,Q18_OTHER,Q19_Part_1,Q19_Part_2,Q19_Part_3,Q19_Part_4,Q19_Part_5,Q19_OTHER,Q27_A_Part_1,Q27_A_Part_2,Q27_A_Part_3,Q27_A_Part_4,Q27_A_Part_5,Q27_A_Part_6,Q27_A_Part_7,Q27_A_Part_8,Q27_A_Part_9,Q27_A_Part_10,Q27_A_Part_11,Q27_A_OTHER,Q28,Q29_A_Part_1,Q29_A_Part_2,Q29_A_Part_3,Q29_A_Part_4,Q29_A_OTHER,Q30_A_Part_1,Q30_A_Part_2,Q30_A_Part_3,Q30_A_Part_4,Q30_A_Part_5,Q30_A_Part_6,Q30_A_Part_7,Q30_A_OTHER,Q31_A_Part_1,Q31_A_Part_2,Q31_A_Part_3,Q31_A_Part_4,Q31_A_Part_5,Q31_A_Part_6,Q31_A_Part_7,Q31_A_Part_8,Q31_A_Part_9,Q31_A_OTHER,Q36_A_Part_1,Q36_A_Part_2,Q36_A_Part_3,Q36_A_Part_4,Q36_A_Part_5,Q36_A_Part_6,Q36_A_Part_7,Q36_A_OTHER,Q37_A_Part_1,Q37_A_Part_2,Q37_A_Part_3,Q37_A_Part_4,Q37_A_Part_5,Q37_A_Part_6,Q37_A_Part_7,Q37_A_OTHER,Q38_A_Part_1,Q38_A_Part_2,Q38_A_Part_3,Q38_A_Part_4,Q38_A_Part_5,Q38_A_Part_6,Q38_A_Part_7,Q38_A_Part_8,Q38_A_Part_9,Q38_A_Part_10,Q38_A_Part_11,Q38_A_OTHER,Q39_Part_1,Q39_Part_2,Q39_Part_3,Q39_Part_4,Q39_Part_5,Q39_Part_6,Q39_Part_7,Q39_Part_8,Q39_Part_9,Q39_OTHER,Q40_Part_1,Q40_Part_2,Q40_Part_3,Q40_Part_4,Q40_Part_5,Q40_Part_6,Q40_Part_7,Q40_Part_8,Q40_Part_9,Q40_Part_10,Q40_Part_11,Q40_OTHER,Q42_Part_1,Q42_Part_2,Q42_Part_3,Q42_Part_4,Q42_Part_5,Q42_Part_6,Q42_Part_7,Q42_Part_8,Q42_Part_9,Q42_Part_10,Q42_Part_11,Q42_OTHER,Q27_B_Part_1,Q27_B_Part_2,Q27_B_Part_3,Q27_B_Part_4,Q27_B_Part_5,Q27_B_Part_6,Q27_B_Part_7,Q27_B_Part_8,Q27_B_Part_9,Q27_B_Part_10,Q27_B_Part_11,Q27_B_OTHER,Q29_B_Part_1,Q29_B_Part_2,Q29_B_Part_3,Q29_B_Part_4,Q29_B_OTHER,Q30_B_Part_1,Q30_B_Part_2,Q30_B_Part_3,Q30_B_Part_4,Q30_B_Part_5,Q30_B_Part_6,Q30_B_Part_7,Q30_B_OTHER,Q31_B_Part_1,Q31_B_Part_2,Q31_B_Part_3,Q31_B_Part_4,Q31_B_Part_5,Q31_B_Part_6,Q31_B_Part_7,Q31_B_Part_8,Q31_B_Part_9,Q31_B_OTHER,Q32_B_Part_1,Q32_B_Part_2,Q32_B_Part_3,Q32_B_Part_4,Q32_B_Part_5,Q32_B_Part_6,Q32_B_Part_7,Q32_B_Part_8,Q32_B_Part_9,Q32_B_Part_10,Q32_B_Part_11,Q32_B_Part_12,Q32_B_Part_13,Q32_B_Part_14,Q32_B_Part_15,Q32_B_Part_16,Q32_B_Part_17,Q32_B_Part_18,Q32_B_Part_19,Q32_B_Part_20,Q32_B_OTHER,Q34_B_Part_1,Q34_B_Part_2,Q34_B_Part_3,Q34_B_Part_4,Q34_B_Part_5,Q34_B_Part_6,Q34_B_Part_7,Q34_B_Part_8,Q34_B_Part_9,Q34_B_Part_10,Q34_B_Part_11,Q34_B_Part_12,Q34_B_Part_13,Q34_B_Part_14,Q34_B_Part_15,Q34_B_Part_16,Q34_B_OTHER,Q36_B_Part_1,Q36_B_Part_2,Q36_B_Part_3,Q36_B_Part_4,Q36_B_Part_5,Q36_B_Part_6,Q36_B_Part_7,Q36_B_OTHER,Q37_B_Part_1,Q37_B_Part_2,Q37_B_Part_3,Q37_B_Part_4,Q37_B_Part_5,Q37_B_Part_6,Q37_B_Part_7,Q37_B_OTHER,Q38_B_Part_1,Q38_B_Part_2,Q38_B_Part_3,Q38_B_Part_4,Q38_B_Part_5,Q38_B_Part_6,Q38_B_Part_7,Q38_B_Part_8,Q38_B_Part_9,Q38_B_Part_10,Q38_B_Part_11,Q38_B_OTHER,Q10
7804,320,18-21,Man,India,Some college/university study without earning ...,Student,1-3 years,Python,A personal computer / desktop,2-5 times,2-3 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Python, C, C++, Javascript, Other","Visual Studio Code (VSCode) , Notepad++","NVIDIA GPUs , Other","Shiny , Other","H2O 3 ,Caret , Other","Linear or Logistic Regression, Bayesian Approa...",NaN,NaN,NaN,Kaggle Notebooks,NaN,NaN,NaN,NaN,NaN,IBM Watson Studio,Amazon Sagemaker Studio Notebooks,NaN,NaN,NaN,NaN,Zeppelin / Zepl Notebooks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DataCamp,NaN,NaN,NaN,LinkedIn Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Amazon Web Services (AWS),NaN,NaN,IBM Cloud / Red Hat,NaN,NaN,NaN,Salesforce Cloud,NaN,NaN,NaN,NaN,NaN,Microsoft Azure Virtual Machines,Google Cloud Compute Engine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Amazon SageMaker,NaN,NaN,NaN,NaN,Dataiku,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Microsoft SQL Server,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Spanner,NaN,NaN,NaN,Amazon QuickSight,NaN,NaN,NaN,NaN,NaN,NaN,Domo,NaN,NaN,NaN,SAP Analytics Cloud,NaN,NaN,NaN,NaN,"Automated data augmentation (e.g. imgaug, albu...",NaN,NaN,Automated model architecture searches (e.g. da...,NaN,NaN,NaN,NaN,NaN,H2O Driverless AI,NaN,DataRobot AutoML,NaN,NaN,NaN,Other,NaN,NaN,Comet.ml,NaN,NaN,NaN,Polyaxon,NaN,NaN,NaN,NaN,NaN,"Kaggle Notebooks, IBM Watson Studio , Amazo..."

In [101]:
df.drop(['Q10_Part_1', 'Q10_Part_2', 'Q10_Part_3', 'Q10_Part_4', 'Q10_Part_5',
       'Q10_Part_6', 'Q10_Part_7', 'Q10_Part_8', 'Q10_Part_9', 'Q10_Part_10',
       'Q10_Part_11', 'Q10_Part_12', 'Q10_Part_13', 'Q10_Part_14',
       'Q10_Part_15', 'Q10_Part_16', 'Q10_OTHER'], axis = 1, inplace = True)
    
df.head(1)

,time,age,gender,Q3,Q4,Q5,Q6,Q8,Q11,Q13,Q15,Q20,Q21,Q22,Q23,Q25,Q26,Q33,Q35,Q41,Q7,Q9,Q12,Q14,Q16,Q17,Q24,Q32,Q34,Q18_Part_1,Q18_Part_2,Q18_Part_3,Q18_Part_4,Q18_Part_5,Q18_Part_6,Q18_OTHER,Q19_Part_1,Q19_Part_2,Q19_Part_3,Q19_Part_4,Q19_Part_5,Q19_OTHER,Q27_A_Part_1,Q27_A_Part_2,Q27_A_Part_3,Q27_A_Part_4,Q27_A_Part_5,Q27_A_Part_6,Q27_A_Part_7,Q27_A_Part_8,Q27_A_Part_9,Q27_A_Part_10,Q27_A_Part_11,Q27_A_OTHER,Q28,Q29_A_Part_1,Q29_A_Part_2,Q29_A_Part_3,Q29_A_Part_4,Q29_A_OTHER,Q30_A_Part_1,Q30_A_Part_2,Q30_A_Part_3,Q30_A_Part_4,Q30_A_Part_5,Q30_A_Part_6,Q30_A_Part_7,Q30_A_OTHER,Q31_A_Part_1,Q31_A_Part_2,Q31_A_Part_3,Q31_A_Part_4,Q31_A_Part_5,Q31_A_Part_6,Q31_A_Part_7,Q31_A_Part_8,Q31_A_Part_9,Q31_A_OTHER,Q36_A_Part_1,Q36_A_Part_2,Q36_A_Part_3,Q36_A_Part_4,Q36_A_Part_5,Q36_A_Part_6,Q36_A_Part_7,Q36_A_OTHER,Q37_A_Part_1,Q37_A_Part_2,Q37_A_Part_3,Q37_A_Part_4,Q37_A_Part_5,Q37_A_Part_6,Q37_A_Part_7,Q37_A_OTHER,Q38_A_Part_1,Q38_A_Part_2,Q38_A_Part_3,Q38_A_Part_4,Q38_A_Part_5,Q38_A_Part_6,Q38_A_Part_7,Q38_A_Part_8,Q38_A_Part_9,Q38_A_Part_10,Q38_A_Part_11,Q38_A_OTHER,Q39_Part_1,Q39_Part_2,Q39_Part_3,Q39_Part_4,Q39_Part_5,Q39_Part_6,Q39_Part_7,Q39_Part_8,Q39_Part_9,Q39_OTHER,Q40_Part_1,Q40_Part_2,Q40_Part_3,Q40_Part_4,Q40_Part_5,Q40_Part_6,Q40_Part_7,Q40_Part_8,Q40_Part_9,Q40_Part_10,Q40_Part_11,Q40_OTHER,Q42_Part_1,Q42_Part_2,Q42_Part_3,Q42_Part_4,Q42_Part_5,Q42_Part_6,Q42_Part_7,Q42_Part_8,Q42_Part_9,Q42_Part_10,Q42_Part_11,Q42_OTHER,Q27_B_Part_1,Q27_B_Part_2,Q27_B_Part_3,Q27_B_Part_4,Q27_B_Part_5,Q27_B_Part_6,Q27_B_Part_7,Q27_B_Part_8,Q27_B_Part_9,Q27_B_Part_10,Q27_B_Part_11,Q27_B_OTHER,Q29_B_Part_1,Q29_B_Part_2,Q29_B_Part_3,Q29_B_Part_4,Q29_B_OTHER,Q30_B_Part_1,Q30_B_Part_2,Q30_B_Part_3,Q30_B_Part_4,Q30_B_Part_5,Q30_B_Part_6,Q30_B_Part_7,Q30_B_OTHER,Q31_B_Part_1,Q31_B_Part_2,Q31_B_Part_3,Q31_B_Part_4,Q31_B_Part_5,Q31_B_Part_6,Q31_B_Part_7,Q31_B_Part_8,Q31_B_Part_9,Q31_B_OTHER,Q32_B_Part_1,Q32_B_Part_2,Q32_B_Part_3,Q32_B_Part_4,Q32_B_Part_5,Q32_B_Part_6,Q32_B_Part_7,Q32_B_Part_8,Q32_B_Part_9,Q32_B_Part_10,Q32_B_Part_11,Q32_B_Part_12,Q32_B_Part_13,Q32_B_Part_14,Q32_B_Part_15,Q32_B_Part_16,Q32_B_Part_17,Q32_B_Part_18,Q32_B_Part_19,Q32_B_Part_20,Q32_B_OTHER,Q34_B_Part_1,Q34_B_Part_2,Q34_B_Part_3,Q34_B_Part_4,Q34_B_Part_5,Q34_B_Part_6,Q34_B_Part_7,Q34_B_Part_8,Q34_B_Part_9,Q34_B_Part_10,Q34_B_Part_11,Q34_B_Part_12,Q34_B_Part_13,Q34_B_Part_14,Q34_B_Part_15,Q34_B_Part_16,Q34_B_OTHER,Q36_B_Part_1,Q36_B_Part_2,Q36_B_Part_3,Q36_B_Part_4,Q36_B_Part_5,Q36_B_Part_6,Q36_B_Part_7,Q36_B_OTHER,Q37_B_Part_1,Q37_B_Part_2,Q37_B_Part_3,Q37_B_Part_4,Q37_B_Part_5,Q37_B_Part_6,Q37_B_Part_7,Q37_B_OTHER,Q38_B_Part_1,Q38_B_Part_2,Q38_B_Part_3,Q38_B_Part_4,Q38_B_Part_5,Q38_B_Part_6,Q38_B_Part_7,Q38_B_Part_8,Q38_B_Part_9,Q38_B_Part_10,Q38_B_Part_11,Q38_B_OTHER,Q10
0,910,50-54,Man,India,Bachelor’s degree,Other,5-10 years,Python,A laptop,2-5 times,5-10 years,Manufacturing/Fabrication,50-249 employees,3-4,No (we do not use ML methods),"25,000-29,999",$100-$999,NaN,NaN,"Local development environments (RStudio, Jupyt...","Python, R",Vim / Emacs,Google Cloud TPUs,"Matplotlib ,Seaborn ,Ggplot / ggplot2 ,Shiny ...","Scikit-learn , TensorFlow ,Caret","Linear or Logistic Regression, Decision Trees ...",None of these activities are an important par...,PostgreSQL,None,"General purpose image/video tools (PIL, cv2, s...",NaN,NaN,NaN,NaN,NaN,NaN,"Word embeddings/vectors (GLoVe, fastText, word...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Platform (GCP),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Compute Engine,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Storage (GCS),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,GitHub,NaN,Kaggle,NaN,NaN,NaN,NaN,Coursera,edX,Kaggle Learn Courses,DataCamp,NaN,Udacity,Udemy,NaN,NaN,NaN,NaN,NaN,NaN,"Email newsletters (Data Elixir, O'Reilly Data ...",NaN,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...","Podcasts (Chai Time Data Science, O’Reilly Dat...","Blogs (Towards Data Science, Analytics Vidhya,...","Journal Publications (peer-reviewed journals, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colab Notebooks

In [102]:
df.shape

(25973, 242)

In [103]:
def union_q18 (columna1,columna2,columa3,columna4,columna5,columna6,columna7):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [104]:
df['Q18'] = df.apply(lambda dataframe: union_q18(dataframe['Q18_Part_1'],dataframe['Q18_Part_2'],dataframe['Q18_Part_3'],dataframe['Q18_Part_4'],
                                          dataframe['Q18_Part_5'],dataframe['Q18_Part_6'], dataframe['Q18_OTHER']), axis = 1)

In [105]:
df.drop(['Q18_Part_1', 'Q18_Part_2', 'Q18_Part_3', 'Q18_Part_4', 'Q18_Part_5',
       'Q18_Part_6', 'Q18_OTHER'], axis = 1, inplace = True)

In [106]:
df.head(1)

,time,age,gender,Q3,Q4,Q5,Q6,Q8,Q11,Q13,Q15,Q20,Q21,Q22,Q23,Q25,Q26,Q33,Q35,Q41,Q7,Q9,Q12,Q14,Q16,Q17,Q24,Q32,Q34,Q19_Part_1,Q19_Part_2,Q19_Part_3,Q19_Part_4,Q19_Part_5,Q19_OTHER,Q27_A_Part_1,Q27_A_Part_2,Q27_A_Part_3,Q27_A_Part_4,Q27_A_Part_5,Q27_A_Part_6,Q27_A_Part_7,Q27_A_Part_8,Q27_A_Part_9,Q27_A_Part_10,Q27_A_Part_11,Q27_A_OTHER,Q28,Q29_A_Part_1,Q29_A_Part_2,Q29_A_Part_3,Q29_A_Part_4,Q29_A_OTHER,Q30_A_Part_1,Q30_A_Part_2,Q30_A_Part_3,Q30_A_Part_4,Q30_A_Part_5,Q30_A_Part_6,Q30_A_Part_7,Q30_A_OTHER,Q31_A_Part_1,Q31_A_Part_2,Q31_A_Part_3,Q31_A_Part_4,Q31_A_Part_5,Q31_A_Part_6,Q31_A_Part_7,Q31_A_Part_8,Q31_A_Part_9,Q31_A_OTHER,Q36_A_Part_1,Q36_A_Part_2,Q36_A_Part_3,Q36_A_Part_4,Q36_A_Part_5,Q36_A_Part_6,Q36_A_Part_7,Q36_A_OTHER,Q37_A_Part_1,Q37_A_Part_2,Q37_A_Part_3,Q37_A_Part_4,Q37_A_Part_5,Q37_A_Part_6,Q37_A_Part_7,Q37_A_OTHER,Q38_A_Part_1,Q38_A_Part_2,Q38_A_Part_3,Q38_A_Part_4,Q38_A_Part_5,Q38_A_Part_6,Q38_A_Part_7,Q38_A_Part_8,Q38_A_Part_9,Q38_A_Part_10,Q38_A_Part_11,Q38_A_OTHER,Q39_Part_1,Q39_Part_2,Q39_Part_3,Q39_Part_4,Q39_Part_5,Q39_Part_6,Q39_Part_7,Q39_Part_8,Q39_Part_9,Q39_OTHER,Q40_Part_1,Q40_Part_2,Q40_Part_3,Q40_Part_4,Q40_Part_5,Q40_Part_6,Q40_Part_7,Q40_Part_8,Q40_Part_9,Q40_Part_10,Q40_Part_11,Q40_OTHER,Q42_Part_1,Q42_Part_2,Q42_Part_3,Q42_Part_4,Q42_Part_5,Q42_Part_6,Q42_Part_7,Q42_Part_8,Q42_Part_9,Q42_Part_10,Q42_Part_11,Q42_OTHER,Q27_B_Part_1,Q27_B_Part_2,Q27_B_Part_3,Q27_B_Part_4,Q27_B_Part_5,Q27_B_Part_6,Q27_B_Part_7,Q27_B_Part_8,Q27_B_Part_9,Q27_B_Part_10,Q27_B_Part_11,Q27_B_OTHER,Q29_B_Part_1,Q29_B_Part_2,Q29_B_Part_3,Q29_B_Part_4,Q29_B_OTHER,Q30_B_Part_1,Q30_B_Part_2,Q30_B_Part_3,Q30_B_Part_4,Q30_B_Part_5,Q30_B_Part_6,Q30_B_Part_7,Q30_B_OTHER,Q31_B_Part_1,Q31_B_Part_2,Q31_B_Part_3,Q31_B_Part_4,Q31_B_Part_5,Q31_B_Part_6,Q31_B_Part_7,Q31_B_Part_8,Q31_B_Part_9,Q31_B_OTHER,Q32_B_Part_1,Q32_B_Part_2,Q32_B_Part_3,Q32_B_Part_4,Q32_B_Part_5,Q32_B_Part_6,Q32_B_Part_7,Q32_B_Part_8,Q32_B_Part_9,Q32_B_Part_10,Q32_B_Part_11,Q32_B_Part_12,Q32_B_Part_13,Q32_B_Part_14,Q32_B_Part_15,Q32_B_Part_16,Q32_B_Part_17,Q32_B_Part_18,Q32_B_Part_19,Q32_B_Part_20,Q32_B_OTHER,Q34_B_Part_1,Q34_B_Part_2,Q34_B_Part_3,Q34_B_Part_4,Q34_B_Part_5,Q34_B_Part_6,Q34_B_Part_7,Q34_B_Part_8,Q34_B_Part_9,Q34_B_Part_10,Q34_B_Part_11,Q34_B_Part_12,Q34_B_Part_13,Q34_B_Part_14,Q34_B_Part_15,Q34_B_Part_16,Q34_B_OTHER,Q36_B_Part_1,Q36_B_Part_2,Q36_B_Part_3,Q36_B_Part_4,Q36_B_Part_5,Q36_B_Part_6,Q36_B_Part_7,Q36_B_OTHER,Q37_B_Part_1,Q37_B_Part_2,Q37_B_Part_3,Q37_B_Part_4,Q37_B_Part_5,Q37_B_Part_6,Q37_B_Part_7,Q37_B_OTHER,Q38_B_Part_1,Q38_B_Part_2,Q38_B_Part_3,Q38_B_Part_4,Q38_B_Part_5,Q38_B_Part_6,Q38_B_Part_7,Q38_B_Part_8,Q38_B_Part_9,Q38_B_Part_10,Q38_B_Part_11,Q38_B_OTHER,Q10,Q18
0,910,50-54,Man,India,Bachelor’s degree,Other,5-10 years,Python,A laptop,2-5 times,5-10 years,Manufacturing/Fabrication,50-249 employees,3-4,No (we do not use ML methods),"25,000-29,999",$100-$999,NaN,NaN,"Local development environments (RStudio, Jupyt...","Python, R",Vim / Emacs,Google Cloud TPUs,"Matplotlib ,Seaborn ,Ggplot / ggplot2 ,Shiny ...","Scikit-learn , TensorFlow ,Caret","Linear or Logistic Regression, Decision Trees ...",None of these activities are an important par...,PostgreSQL,None,"Word embeddings/vectors (GLoVe, fastText, word...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Platform (GCP),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Compute Engine,NaN,NaN,NaN,NaN,NaN,NaN,Google Cloud Storage (GCS),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No / None,NaN,NaN,NaN,NaN,GitHub,NaN,Kaggle,NaN,NaN,NaN,NaN,Coursera,edX,Kaggle Learn Courses,DataCamp,NaN,Udacity,Udemy,NaN,NaN,NaN,NaN,NaN,NaN,"Email newsletters (Data Elixir, O'Reilly Data ...",NaN,"Kaggle (notebooks, forums, etc)",NaN,"YouTube (Kaggle YouTube, Cloud AI Adventures, ...","Podcasts (Chai Time Data Science, O’Reilly Dat...","Blogs (Towards Data Science, Analytics Vidhya,...","Journal Publications (peer-reviewed journals, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Colab Notebooks,"General purpose image/video tools (PIL, cv2, s..."

In [107]:
df.shape

(25973, 236)

In [108]:
def union_q19 (columna1,columna2,columa3,columna4,columna5,columna6):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [109]:
df['Q19'] = df.apply(lambda dataframe: union_q19(dataframe['Q19_Part_1'],dataframe['Q19_Part_2'],dataframe['Q19_Part_3'],dataframe['Q19_Part_4'],
                                          dataframe['Q19_Part_5'], dataframe['Q19_OTHER']), axis = 1)

In [110]:
df.drop(['Q19_Part_1', 'Q19_Part_2', 'Q19_Part_3', 'Q19_Part_4', 'Q19_Part_5',
       'Q19_OTHER'], axis = 1, inplace = True)

In [111]:
df.shape

(25973, 231)

In [112]:
def union_q27A (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [113]:
df['Q27-A'] = df.apply(lambda dataframe: union_q27A(dataframe['Q27_A_Part_1'],dataframe['Q27_A_Part_2'],dataframe['Q27_A_Part_3'],
                                                    dataframe['Q27_A_Part_4'], dataframe['Q27_A_Part_5'], dataframe['Q27_A_Part_6'],
                                                    dataframe['Q27_A_Part_7'], dataframe['Q27_A_Part_8'], dataframe['Q27_A_Part_9'],
                                                    dataframe['Q27_A_Part_10'], dataframe['Q27_A_Part_11'], dataframe['Q27_A_OTHER']), axis = 1)

In [114]:
df.drop(['Q27_A_Part_1', 'Q27_A_Part_2', 'Q27_A_Part_3', 'Q27_A_Part_4', 'Q27_A_Part_5', 
        'Q27_A_Part_6', 'Q27_A_Part_7', 'Q27_A_Part_8', 'Q27_A_Part_9', 'Q27_A_Part_10', 'Q27_A_Part_11', 'Q27_A_OTHER'], 
        axis = 1, inplace = True)

In [115]:
df.shape

(25973, 220)

In [116]:
def union_q29A (columna1,columna2,columa3,columna4,columna5):
    lista = [columna1,columna2,columa3,columna4,columna5]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [117]:
df['Q29-A'] = df.apply(lambda dataframe: union_q29A(dataframe['Q29_A_Part_1'],dataframe['Q29_A_Part_2'],dataframe['Q29_A_Part_3'],
                                                    dataframe['Q29_A_Part_4'], dataframe['Q29_A_OTHER']), axis = 1)

In [118]:
df.drop(['Q29_A_Part_1', 'Q29_A_Part_2', 'Q29_A_Part_3', 'Q29_A_Part_4',
       'Q29_A_OTHER'], axis = 1, inplace = True)

In [119]:
df.shape

(25973, 216)

In [120]:
def union_q30A (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [121]:
df['Q30-A'] = df.apply(lambda dataframe: union_q30A(dataframe['Q30_A_Part_1'],dataframe['Q30_A_Part_2'],dataframe['Q30_A_Part_3'],
                                                    dataframe['Q30_A_Part_4'], dataframe['Q30_A_Part_5'], dataframe['Q30_A_Part_6'],
                                                     dataframe['Q30_A_Part_7'], dataframe['Q30_A_OTHER']), axis = 1)

In [122]:
df.drop(['Q30_A_Part_1', 'Q30_A_Part_2', 'Q30_A_Part_3', 'Q30_A_Part_4',
       'Q30_A_Part_5', 'Q30_A_Part_6', 'Q30_A_Part_7', 'Q30_A_OTHER'], axis = 1, inplace = True)

In [123]:
df.shape

(25973, 209)

In [124]:
def union_q31A (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8, columna9, columna10):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8, columna9, columna10]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [125]:
df['Q31-A'] = df.apply(lambda dataframe: union_q31A(dataframe['Q31_A_Part_1'],dataframe['Q31_A_Part_2'],dataframe['Q31_A_Part_3'],
                                                    dataframe['Q31_A_Part_4'], dataframe['Q31_A_Part_5'], dataframe['Q31_A_Part_6'],
                                                     dataframe['Q31_A_Part_7'], dataframe['Q31_A_Part_8'],dataframe['Q31_A_Part_9'], 
                                                     dataframe['Q31_A_OTHER']), axis = 1)

In [126]:
df.drop(['Q31_A_Part_1', 'Q31_A_Part_2', 'Q31_A_Part_3', 'Q31_A_Part_4',
       'Q31_A_Part_5', 'Q31_A_Part_6', 'Q31_A_Part_7', 'Q31_A_Part_8',
       'Q31_A_Part_9', 'Q31_A_OTHER'], axis = 1, inplace = True)

In [127]:
df.shape

(25973, 200)

In [128]:
def union_q36A (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [129]:
df['Q36-A'] = df.apply(lambda dataframe: union_q36A(dataframe['Q36_A_Part_1'],dataframe['Q36_A_Part_2'],dataframe['Q36_A_Part_3'],
                                                    dataframe['Q36_A_Part_4'], dataframe['Q36_A_Part_5'], dataframe['Q36_A_Part_6'],
                                                     dataframe['Q36_A_Part_7'], dataframe['Q36_A_OTHER']), axis = 1)

In [130]:
df.drop(['Q36_A_Part_1', 'Q36_A_Part_2', 'Q36_A_Part_3', 'Q36_A_Part_4',
       'Q36_A_Part_5', 'Q36_A_Part_6', 'Q36_A_Part_7', 'Q36_A_OTHER'], axis = 1, inplace = True)

In [131]:
df.shape

(25973, 193)

In [132]:
def union_q37A (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [133]:
df['Q37-A'] = df.apply(lambda dataframe: union_q37A(dataframe['Q37_A_Part_1'],dataframe['Q37_A_Part_2'],dataframe['Q37_A_Part_3'],
                                                    dataframe['Q37_A_Part_4'], dataframe['Q37_A_Part_5'], dataframe['Q37_A_Part_6'],
                                                     dataframe['Q37_A_Part_7'], dataframe['Q37_A_OTHER']), axis = 1)

In [134]:
df.drop(['Q37_A_Part_1', 'Q37_A_Part_2', 'Q37_A_Part_3', 'Q37_A_Part_4',
       'Q37_A_Part_5', 'Q37_A_Part_6', 'Q37_A_Part_7', 'Q37_A_OTHER'], axis = 1, inplace = True)

In [135]:
df.shape

(25973, 186)

In [136]:
def union_q38A (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [137]:
df['Q38-A'] = df.apply(lambda dataframe: union_q38A(dataframe['Q38_A_Part_1'],dataframe['Q38_A_Part_2'],dataframe['Q38_A_Part_3'],
                                                    dataframe['Q38_A_Part_4'], dataframe['Q38_A_Part_5'], dataframe['Q38_A_Part_6'],
                                                    dataframe['Q38_A_Part_7'], dataframe['Q38_A_Part_8'], dataframe['Q38_A_Part_9'],
                                                    dataframe['Q38_A_Part_10'], dataframe['Q38_A_Part_11'], dataframe['Q38_A_OTHER']), axis = 1)

In [138]:
df.drop(['Q38_A_Part_1', 'Q38_A_Part_2', 'Q38_A_Part_3', 'Q38_A_Part_4',
       'Q38_A_Part_5', 'Q38_A_Part_6', 'Q38_A_Part_7', 'Q38_A_Part_8',
       'Q38_A_Part_9', 'Q38_A_Part_10', 'Q38_A_Part_11', 'Q38_A_OTHER'], axis = 1, inplace = True)

In [139]:
df.shape

(25973, 175)

In [140]:
def union_q39 (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [141]:
df['Q39'] = df.apply(lambda dataframe: union_q39(dataframe['Q39_Part_1'],dataframe['Q39_Part_2'],dataframe['Q39_Part_3'],
                                                    dataframe['Q39_Part_4'], dataframe['Q39_Part_5'], dataframe['Q39_Part_6'],
                                                    dataframe['Q39_Part_7'], dataframe['Q39_Part_8'], dataframe['Q39_Part_9'],
                                                    dataframe['Q39_OTHER']), axis = 1)

In [142]:
df.drop(['Q39_Part_1', 'Q39_Part_2', 'Q39_Part_3', 'Q39_Part_4', 'Q39_Part_5',
       'Q39_Part_6', 'Q39_Part_7', 'Q39_Part_8', 'Q39_Part_9', 'Q39_OTHER'], axis = 1, inplace = True)

In [143]:
df.shape

(25973, 166)

In [144]:
def union_q40 (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [145]:
df['Q40'] = df.apply(lambda dataframe: union_q40(dataframe['Q40_Part_1'],dataframe['Q40_Part_2'],dataframe['Q40_Part_3'],
                                                    dataframe['Q40_Part_4'], dataframe['Q40_Part_5'], dataframe['Q40_Part_6'],
                                                    dataframe['Q40_Part_7'], dataframe['Q40_Part_8'], dataframe['Q40_Part_9'],
                                                    dataframe['Q40_Part_10'], dataframe['Q40_Part_11'], dataframe['Q40_OTHER']), axis = 1)

In [146]:
df.drop(['Q40_Part_1', 'Q40_Part_2', 'Q40_Part_3', 'Q40_Part_4', 'Q40_Part_5',
      'Q40_Part_6', 'Q40_Part_7', 'Q40_Part_8', 'Q40_Part_9', 'Q40_Part_10', 'Q40_Part_11', 'Q40_OTHER'], axis = 1, inplace = True)

In [147]:
df.shape

(25973, 155)

In [148]:
def union_q42 (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [149]:
df['Q42'] = df.apply(lambda dataframe: union_q42(dataframe['Q42_Part_1'],dataframe['Q42_Part_2'],dataframe['Q42_Part_3'],
                                                    dataframe['Q42_Part_4'], dataframe['Q42_Part_5'], dataframe['Q42_Part_6'],
                                                    dataframe['Q42_Part_7'], dataframe['Q42_Part_8'], dataframe['Q42_Part_9'],
                                                    dataframe['Q42_Part_10'], dataframe['Q42_Part_11'], dataframe['Q42_OTHER']), axis = 1)

In [150]:
df.drop(['Q42_Part_1', 'Q42_Part_2', 'Q42_Part_3', 'Q42_Part_4', 'Q42_Part_5',
       'Q42_Part_6', 'Q42_Part_7', 'Q42_Part_8', 'Q42_Part_9', 'Q42_Part_10', 'Q42_Part_11', 'Q42_OTHER'], axis = 1, inplace = True)

In [151]:
df.shape

(25973, 144)

In [152]:
def union_q27B (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [153]:
df['Q27-B'] = df.apply(lambda dataframe: union_q27B(dataframe['Q27_B_Part_1'],dataframe['Q27_B_Part_2'],dataframe['Q27_B_Part_3'],
                                                    dataframe['Q27_B_Part_4'], dataframe['Q27_B_Part_5'], dataframe['Q27_B_Part_6'],
                                                    dataframe['Q27_B_Part_7'], dataframe['Q27_B_Part_8'], dataframe['Q27_B_Part_9'],
                                                    dataframe['Q27_B_Part_10'], dataframe['Q27_B_Part_11'], dataframe['Q27_B_OTHER']), axis = 1)

In [154]:
df.drop(['Q27_B_Part_1', 'Q27_B_Part_2', 'Q27_B_Part_3', 'Q27_B_Part_4',
       'Q27_B_Part_5', 'Q27_B_Part_6', 'Q27_B_Part_7', 'Q27_B_Part_8',
       'Q27_B_Part_9', 'Q27_B_Part_10','Q27_B_Part_11', 'Q27_B_OTHER'], axis = 1, inplace = True)

In [155]:
df.shape

(25973, 133)

In [156]:
def union_q29B (columna1,columna2,columa3,columna4,columna5):
    lista = [columna1,columna2,columa3,columna4,columna5]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [157]:
df['Q29-B'] = df.apply(lambda dataframe: union_q29B(dataframe['Q29_B_Part_1'],dataframe['Q29_B_Part_2'],dataframe['Q29_B_Part_3'],
                                                    dataframe['Q29_B_Part_4'], dataframe['Q29_B_OTHER']), axis = 1)

In [158]:
df.drop(['Q29_B_Part_1', 'Q29_B_Part_2', 'Q29_B_Part_3', 'Q29_B_Part_4',
       'Q29_B_OTHER'], axis = 1, inplace = True)

In [159]:
df.shape

(25973, 129)

In [160]:
def union_q30B (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [161]:
df['Q30-B'] = df.apply(lambda dataframe: union_q30B(dataframe['Q30_B_Part_1'],dataframe['Q30_B_Part_2'],dataframe['Q30_B_Part_3'],
                                                    dataframe['Q30_B_Part_4'], dataframe['Q30_B_Part_5'], dataframe['Q30_B_Part_6'],
                                                     dataframe['Q30_B_Part_7'], dataframe['Q30_B_OTHER']), axis = 1)

In [162]:
df.drop(['Q30_B_Part_1', 'Q30_B_Part_2', 'Q30_B_Part_3', 'Q30_B_Part_4',
       'Q30_B_Part_5', 'Q30_B_Part_6', 'Q30_B_Part_7', 'Q30_B_OTHER'], axis = 1, inplace = True)

In [163]:
df.shape

(25973, 122)

In [164]:
def union_q31B (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8, columna9, columna10):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8, columna9, columna10]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [165]:
df['Q31-B'] = df.apply(lambda dataframe: union_q31B(dataframe['Q31_B_Part_1'],dataframe['Q31_B_Part_2'],dataframe['Q31_B_Part_3'],
                                                    dataframe['Q31_B_Part_4'], dataframe['Q31_B_Part_5'], dataframe['Q31_B_Part_6'],
                                                     dataframe['Q31_B_Part_7'], dataframe['Q31_B_Part_8'],dataframe['Q31_B_Part_9'], 
                                                     dataframe['Q31_B_OTHER']), axis = 1)

In [166]:
df.drop(['Q31_B_Part_1', 'Q31_B_Part_2', 'Q31_B_Part_3', 'Q31_B_Part_4',
       'Q31_B_Part_5', 'Q31_B_Part_6', 'Q31_B_Part_7', 'Q31_B_Part_8',
       'Q31_B_Part_9', 'Q31_B_OTHER'], axis = 1, inplace = True)

In [167]:
def union_q32B (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12,
                columna13, columna14, columna15, columna16, columna17, columna18, columna19, columna20, columna21):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12,
             columna13, columna14, columna15, columna16, columna17, columna18, columna19, columna20, columna21]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [168]:
df['Q32-B'] = df.apply(lambda dataframe: union_q32B(dataframe['Q32_B_Part_1'],dataframe['Q32_B_Part_2'],dataframe['Q32_B_Part_3'],
                                                    dataframe['Q32_B_Part_4'], dataframe['Q32_B_Part_5'], dataframe['Q32_B_Part_6'],
                                                    dataframe['Q32_B_Part_7'], dataframe['Q32_B_Part_8'], dataframe['Q32_B_Part_9'],
                                                    dataframe['Q32_B_Part_10'], dataframe['Q32_B_Part_11'], dataframe['Q32_B_Part_12'],
                                                    dataframe['Q32_B_Part_13'], dataframe['Q32_B_Part_14'], dataframe['Q32_B_Part_15'],
                                                    dataframe['Q32_B_Part_16'], dataframe['Q32_B_Part_17'], dataframe['Q32_B_Part_18'],
                                                    dataframe['Q32_B_Part_19'], dataframe['Q32_B_Part_20'], dataframe['Q32_B_OTHER']), axis = 1)

In [169]:
df.drop(['Q32_B_Part_1', 'Q32_B_Part_2', 'Q32_B_Part_3', 'Q32_B_Part_4',
       'Q32_B_Part_5', 'Q32_B_Part_6', 'Q32_B_Part_7', 'Q32_B_Part_8',
       'Q32_B_Part_9', 'Q32_B_Part_10', 'Q32_B_Part_11', 'Q32_B_Part_12',
       'Q32_B_Part_13', 'Q32_B_Part_14', 'Q32_B_Part_15', 'Q32_B_Part_16',
       'Q32_B_Part_17', 'Q32_B_Part_18', 'Q32_B_Part_19', 'Q32_B_Part_20',
       'Q32_B_OTHER'], axis = 1, inplace = True)

In [170]:
df.shape

(25973, 93)

In [171]:
def union_q34B (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12,
                columna13, columna14, columna15, columna16, columna17):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12,
             columna13, columna14, columna15, columna16, columna17]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [172]:
df['Q34-B'] = df.apply(lambda dataframe: union_q34B(dataframe['Q34_B_Part_1'], dataframe['Q34_B_Part_2'], dataframe['Q34_B_Part_3'],
                                                    dataframe['Q34_B_Part_4'], dataframe['Q34_B_Part_5'], dataframe['Q34_B_Part_6'],
                                                    dataframe['Q34_B_Part_7'], dataframe['Q34_B_Part_8'], dataframe['Q34_B_Part_9'],
                                                    dataframe['Q34_B_Part_10'], dataframe['Q34_B_Part_11'], dataframe['Q34_B_Part_12'],
                                                    dataframe['Q34_B_Part_13'], dataframe['Q34_B_Part_14'], dataframe['Q34_B_Part_15'],
                                                    dataframe['Q34_B_Part_16'], dataframe['Q34_B_OTHER']), axis = 1)

In [173]:
df.drop(['Q34_B_Part_1', 'Q34_B_Part_2', 'Q34_B_Part_3', 'Q34_B_Part_4',
       'Q34_B_Part_5', 'Q34_B_Part_6', 'Q34_B_Part_7', 'Q34_B_Part_8',
       'Q34_B_Part_9', 'Q34_B_Part_10', 'Q34_B_Part_11', 'Q34_B_Part_12',
       'Q34_B_Part_13', 'Q34_B_Part_14', 'Q34_B_Part_15', 'Q34_B_Part_16',
       'Q34_B_OTHER'], axis = 1, inplace = True)

In [174]:
df.shape

(25973, 77)

In [175]:
def union_q36B (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [176]:
df['Q36-B'] = df.apply(lambda dataframe: union_q36B(dataframe['Q36_B_Part_1'],dataframe['Q36_B_Part_2'],dataframe['Q36_B_Part_3'],
                                                    dataframe['Q36_B_Part_4'], dataframe['Q36_B_Part_5'], dataframe['Q36_B_Part_6'],
                                                     dataframe['Q36_B_Part_7'], dataframe['Q36_B_OTHER']), axis = 1)

In [177]:
df.drop(['Q36_B_Part_1', 'Q36_B_Part_2', 'Q36_B_Part_3', 'Q36_B_Part_4',
       'Q36_B_Part_5', 'Q36_B_Part_6', 'Q36_B_Part_7', 'Q36_B_OTHER'], axis = 1, inplace = True)

In [178]:
df.shape

(25973, 70)

In [179]:
def union_q37B (columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8):
    lista = [columna1,columna2,columa3,columna4,columna5, columna6, columna7, columna8]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [180]:
df['Q37-B'] = df.apply(lambda dataframe: union_q37B(dataframe['Q37_B_Part_1'],dataframe['Q37_B_Part_2'],dataframe['Q37_B_Part_3'],
                                                    dataframe['Q37_B_Part_4'], dataframe['Q37_B_Part_5'], dataframe['Q37_B_Part_6'],
                                                     dataframe['Q37_B_Part_7'], dataframe['Q37_B_OTHER']), axis = 1)

In [181]:
df.drop(['Q37_B_Part_1', 'Q37_B_Part_2', 'Q37_B_Part_3', 'Q37_B_Part_4',
       'Q37_B_Part_5', 'Q37_B_Part_6', 'Q37_B_Part_7', 'Q37_B_OTHER'], axis = 1, inplace = True)

In [182]:
df.shape

(25973, 63)

In [ ]:
def union_q38B (columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12):
    lista = [columna1,columna2,columa3,columna4,columna5,columna6,columna7,columna8,columna9,columna10,columna11,columna12]
    lista_str = [str(x) for x in lista]
    lista_final = []
    for i in lista_str:
        if i.lower() not in ['nan']:
            lista_final.append(i)
    texto = ', '.join(lista_final)    
    return texto

In [ ]:
df['Q38-B'] = df.apply(lambda dataframe: union_q38B(dataframe['Q38_B_Part_1'],dataframe['Q38_B_Part_2'],dataframe['Q38_B_Part_3'],
                                                    dataframe['Q38_B_Part_4'], dataframe['Q38_B_Part_5'], dataframe['Q38_B_Part_6'],
                                                    dataframe['Q38_B_Part_7'], dataframe['Q38_B_Part_8'], dataframe['Q38_B_Part_9'],
                                                    dataframe['Q38_B_Part_10'], dataframe['Q38_B_Part_11'], dataframe['Q38_B_OTHER']), axis = 1)

In [183]:
df.drop(['Q38_B_Part_1', 'Q38_B_Part_2', 'Q38_B_Part_3', 'Q38_B_Part_4',
       'Q38_B_Part_5', 'Q38_B_Part_6', 'Q38_B_Part_7', 'Q38_B_Part_8',
       'Q38_B_Part_9', 'Q38_B_Part_10', 'Q38_B_Part_11', 'Q38_B_OTHER'], axis = 1, inplace = True)

In [184]:
df.shape

(25973, 51)

In [186]:
df.head(1)

,time,age,gender,Q3,Q4,Q5,Q6,Q8,Q11,Q13,Q15,Q20,Q21,Q22,Q23,Q25,Q26,Q33,Q35,Q41,Q7,Q9,Q12,Q14,Q16,Q17,Q24,Q32,Q34,Q28,Q10,Q18,Q19,Q27-A,Q29-A,Q30-A,Q31-A,Q36-A,Q37-A,Q38-A,Q39,Q40,Q42,Q27-B,Q29-B,Q30-B,Q31-B,Q32-B,Q34-B,Q36-B,Q37-B
0,910,50-54,Man,India,Bachelor’s degree,Other,5-10 years,Python,A laptop,2-5 times,5-10 years,Manufacturing/Fabrication,50-249 employees,3-4,No (we do not use ML methods),"25,000-29,999",$100-$999,NaN,NaN,"Local development environments (RStudio, Jupyt...","Python, R",Vim / Emacs,Google Cloud TPUs,"Matplotlib ,Seaborn ,Ggplot / ggplot2 ,Shiny ...","Scikit-learn , TensorFlow ,Caret","Linear or Logistic Regression, Decision Trees ...",None of these activities are an important par...,PostgreSQL,None,NaN,Colab Notebooks,"General purpose image/video tools (PIL, cv2, s...","Word embeddings/vectors (GLoVe, fastText, word...",Google Cloud Platform (GCP),Google Cloud Compute Engine,Google Cloud Storage (GCS),No / None,No / None,,No / None,"GitHub , Kaggle","Coursera, edX, Kaggle Learn Courses, DataCamp,...","Email newsletters (Data Elixir, O'Reilly Data ...",,,,,,,,